//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ekzamen
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public int IdEvent { get; set; }
        public string Title { get; set; }
        public string DataTime { get; set; }
        public Nullable<int> Days { get; set; }
        public Nullable<int> IdCity { get; set; }
    
        public virtual City City { get; set; }
    }
}
