//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ekzamen
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int IdUser { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Post { get; set; }
        public string Phone { get; set; }
        public string BirthDay { get; set; }
        public Nullable<int> IdGender { get; set; }
        public Nullable<int> IdCountry { get; set; }
        public Nullable<int> IdNapravlenie { get; set; }
        public Nullable<int> IdMeropriyatie { get; set; }
        public string Password { get; set; }
        public Nullable<int> IdGrade { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual Gender Gender { get; set; }
        public virtual Grade Grade { get; set; }
        public virtual Meropriyatie Meropriyatie { get; set; }
        public virtual Napravlenie Napravlenie { get; set; }
    }
}
